export const URLS = {
  HOME: "/",
  COURSES: "/courses",
  SHOP: "/shop",
  EVENTS: "/events",
  ABOUT_US: "/about",
  CONTACT_US: "/contact",
  FAQS: "/faqs",
  CART: "/cart",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PROFILE: "/profile",
  ORDERS: "/profile/orders",
  BOOKED_EVENTS: "/profile/events",
};
